# SonataAdminBundle Configuration
sonata_admin:
    templates:
        layout:  ApplicationSonataAdminBundle::standard_layout.html.twig
#    assets:
#        javascripts:
#            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
#            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
#        stylesheets:
#            - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
#            - bundles/sonataadmin/vendor/jqueryui/themes/flick/jquery-ui.min.css